<?php

class InstanceManagerServiceProvider extends \Illuminate\Support\ServiceProvider {

	public function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
	}

	public function register()
	{
		$this->app->bindShared('instance-manager', function($app) {
			return new LaravelInstanceManager();
		});
	}
}